{
  "name": "9c7510dd-9aec-4045-8a12-e8f92f71a1ee",
  "compatibilityLevel": 1520,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Dates",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "formatString": "dd mmmm yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"LongDate\" FormatString=\"dd MMMM yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "QuarterOfYear",
            "dataType": "int64",
            "sourceColumn": "QuarterOfYear",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "MonthOfYear",
            "dataType": "int64",
            "sourceColumn": "MonthOfYear",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "DayOfMonth",
            "dataType": "int64",
            "sourceColumn": "DayOfMonth",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "DateInt",
            "dataType": "int64",
            "sourceColumn": "DateInt",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "Month Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Month & Year",
            "dataType": "string",
            "sourceColumn": "Month & Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Quarter & Year",
            "dataType": "string",
            "sourceColumn": "Quarter & Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "DayOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayOfWeek",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "DayOfWeekName",
            "dataType": "string",
            "sourceColumn": "DayOfWeekName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "WeekEnding",
            "dataType": "dateTime",
            "sourceColumn": "WeekEnding",
            "formatString": "dd mmmm yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"LongDate\" FormatString=\"dd MMMM yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "MonthEnding",
            "dataType": "dateTime",
            "sourceColumn": "MonthEnding",
            "formatString": "dd mmmm yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"LongDate\" FormatString=\"dd MMMM yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "ISO Weeknumber",
            "dataType": "int64",
            "sourceColumn": "ISO Weeknumber",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "ISO Year",
            "dataType": "int64",
            "sourceColumn": "ISO Year",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "ISO Day of Year",
            "dataType": "int64",
            "sourceColumn": "ISO Day of Year",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Week & Year",
            "dataType": "string",
            "sourceColumn": "Week & Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "WeeknYear",
            "dataType": "int64",
            "sourceColumn": "WeeknYear",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "MonthnYear",
            "dataType": "int64",
            "sourceColumn": "MonthnYear",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "QuarternYear",
            "dataType": "int64",
            "sourceColumn": "QuarternYear",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Fiscal Year",
            "dataType": "string",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Fiscal Quarter",
            "dataType": "string",
            "sourceColumn": "Fiscal Quarter",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Fiscal Period",
            "dataType": "int64",
            "sourceColumn": "Fiscal Period",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "IsAfterToday",
            "dataType": "boolean",
            "sourceColumn": "IsAfterToday",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "IsWorkingDay",
            "dataType": "boolean",
            "sourceColumn": "IsWorkingDay",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "IsHoliday",
            "dataType": "string",
            "sourceColumn": "IsHoliday",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "IsBusinessDay",
            "dataType": "boolean",
            "sourceColumn": "IsBusinessDay",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "Day Type",
            "dataType": "string",
            "sourceColumn": "Day Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "WeekOffset",
            "dataType": "int64",
            "sourceColumn": "WeekOffset",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "MonthOffset",
            "dataType": "int64",
            "sourceColumn": "MonthOffset",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "QuarterOffset",
            "dataType": "int64",
            "sourceColumn": "QuarterOffset",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "YearOffset",
            "dataType": "int64",
            "sourceColumn": "YearOffset",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "FiscalYearOffset",
            "dataType": "int64",
            "sourceColumn": "FiscalYearOffset",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "WeekCompleted",
            "dataType": "boolean",
            "sourceColumn": "WeekCompleted",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "MonthCompleted",
            "dataType": "boolean",
            "sourceColumn": "MonthCompleted",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "name": "QuarterCompleted",
            "dataType": "boolean",
            "sourceColumn": "QuarterCompleted",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Previous Two Years",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR TwoYears = MAX( 'Complaints Data'[Complain Date] ) - (365 * 2 )",
              "VAR MaxDate = MAX( 'Complaints Data'[Completion Date] )",
              "",
              "RETURN",
              "IF( AND( Dates[Date] > TwoYears, Dates[Date] < MaxDate ), True, FALSE() )"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dates-c067c12e-9ee3-47fa-9ef2-ec3e240bb138",
            "mode": "import",
            "queryGroup": "Data Model",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"Dates Query\"(#date(2017, 1, 1), #date(2021, 12, 31), 7, null, null)",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DateTableTemplate_e6a38236-00e5-4a51-866c-8d18b5e353ec",
        "isHidden": true,
        "isPrivate": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_e6a38236-00e5-4a51-866c-8d18b5e353ec-654c591e-412a-4270-b845-6d824ab49cf5",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "Regions",
        "columns": [
          {
            "name": "id",
            "dataType": "int64",
            "sourceColumn": "id",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "county",
            "dataType": "string",
            "sourceColumn": "county",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "State Code",
            "dataType": "string",
            "sourceColumn": "State Code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "States",
            "dataType": "string",
            "sourceColumn": "States",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "type",
            "dataType": "string",
            "sourceColumn": "type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "latitude",
            "dataType": "double",
            "sourceColumn": "latitude",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "longitude",
            "dataType": "double",
            "sourceColumn": "longitude",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "time_zone",
            "dataType": "string",
            "sourceColumn": "time_zone",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "State Regions",
            "dataType": "string",
            "sourceColumn": "State Regions",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Regions-fc7c3043-fd4a-4aaf-a5ba-07d6820d9a0a",
            "mode": "import",
            "queryGroup": "Data Model",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\OneDrive - EnterpriseDNA\\VIRTUAL TRAINING\\Power BI Challenges\\Insurance Complaints\\Insurance - Complain Administration.xlsx\"), null, true),",
                "    Regions_Tbl_Table = Source{[Item=\"Regions_Tbl\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Regions_Tbl_Table,{{\"id\", Int64.Type}, {\"name\", type text}, {\"county\", type text}, {\"state_code\", type text}, {\"state\", type text}, {\"type\", type text}, {\"latitude\", type number}, {\"longitude\", type number}, {\"area_code\", Int64.Type}, {\"population\", Int64.Type}, {\"households\", Int64.Type}, {\"median_income\", Int64.Type}, {\"land_area\", Int64.Type}, {\"water_area\", Int64.Type}, {\"time_zone\", type text}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"state_code\"}, #\"State Regions\", {\"State Code\"}, \"State Regions\", JoinKind.LeftOuter),",
                "    #\"Expanded State Regions\" = Table.ExpandTableColumn(#\"Merged Queries\", \"State Regions\", {\"Region\"}, {\"State Regions.Region\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded State Regions\",{\"area_code\", \"population\", \"households\", \"median_income\", \"land_area\", \"water_area\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"State Regions.Region\", \"State Regions\"}, {\"state\", \"States\"}, {\"state_code\", \"State Code\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Statuses",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Statuses-72fe01ef-e210-492a-beb0-45f073c663bb",
            "mode": "import",
            "queryGroup": "Data Model",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\OneDrive - EnterpriseDNA\\VIRTUAL TRAINING\\Power BI Challenges\\Insurance Complaints\\Insurance - Complain Administration.xlsx\"), null, true),",
                "    Statuses_Tbl_Table = Source{[Item=\"Statuses_Tbl\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Statuses_Tbl_Table,{{\"ID\", Int64.Type}, {\"Description\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Description\", \"Status\"}}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Renamed Columns\",{{\"Status\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Complaints Data",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Complain Date",
            "dataType": "dateTime",
            "sourceColumn": "Complain Date",
            "formatString": "dd/mm/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"2057\" Group=\"ShortDate\" FormatString=\"dd/MM/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Completion Date",
            "dataType": "dateTime",
            "sourceColumn": "Completion Date",
            "formatString": "dd/mm/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"2057\" Group=\"ShortDate\" FormatString=\"dd/MM/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "CustomerID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "BrokerID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrokerID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "ProductID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "ComplainPriorityID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ComplainPriorityID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "ComplainTypeID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ComplainTypeID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "ComplainSourceID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ComplainSourceID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "ComplainCategoryID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ComplainCategoryID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "ComplainStatusID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ComplainStatusID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "AdministratorID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AdministratorID",
            "formatString": "0",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Satisfaction Level",
            "dataType": "string",
            "sourceColumn": "Satisfaction Level",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "ExpectedReimbursement",
            "dataType": "int64",
            "sourceColumn": "ExpectedReimbursement",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Days To Resolution",
            "dataType": "int64",
            "sourceColumn": "Days To Resolution",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Days Since Complaint",
            "dataType": "int64",
            "sourceColumn": "Days Since Complaint",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Complaints Data-b4e008dc-1cb8-4d46-bea6-dd121d26bc13",
            "mode": "import",
            "queryGroup": "Data Model",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\OneDrive - EnterpriseDNA\\VIRTUAL TRAINING\\Power BI Challenges\\Insurance Complaints\\Insurance - Complain Administration.xlsx\"), null, true),",
                "    ComplainsData_Tbl_Table = Source{[Item=\"ComplainsData_Tbl\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(ComplainsData_Tbl_Table,{{\"ID\", Int64.Type}, {\"ComplainDate\", type date}, {\"CompletionDate\", type date}, {\"CustomerID\", Int64.Type}, {\"BrokerID\", Int64.Type}, {\"ProductID\", Int64.Type}, {\"ComplainPriorityID\", Int64.Type}, {\"ComplainTypeID\", Int64.Type}, {\"ComplainSourceID\", Int64.Type}, {\"ComplainCategoryID\", Int64.Type}, {\"ComplainStatusID\", Int64.Type}, {\"AdministratorID\", Int64.Type}, {\"ClientSatisfaction\", type text}, {\"ExpectedReimbursement\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"ComplainDate\", \"Complain Date\"}, {\"CompletionDate\", \"Completion Date\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"SAT\",\"Satisfied\",Replacer.ReplaceText,{\"ClientSatisfaction\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"NSA\",\"Not Satisfied\",Replacer.ReplaceText,{\"ClientSatisfaction\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"N/A\",\"No Data\",Replacer.ReplaceText,{\"ClientSatisfaction\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Replaced Value2\",{{\"ClientSatisfaction\", \"Satisfaction Level\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns1\", \"Days To Resolution\", each [Completion Date] - [Complain Date]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Days To Resolution\", Int64.Type}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type1\", \"Days Since Complaint\", each Date.From(DateTime.LocalNow()) - [Complain Date]),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Days Since Complaint\", Int64.Type}})",
                "in",
                "    #\"Changed Type3\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Types",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Channel Type",
            "dataType": "string",
            "sourceColumn": "Channel Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Types-49d04972-8264-4178-a2cc-9116abd049d1",
            "mode": "import",
            "queryGroup": "Data Model",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\OneDrive - EnterpriseDNA\\VIRTUAL TRAINING\\Power BI Challenges\\Insurance Complaints\\Insurance - Complain Administration.xlsx\"), null, true),",
                "    Types_Tbl_Table = Source{[Item=\"Types_Tbl\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Types_Tbl_Table,{{\"ID\", Int64.Type}, {\"Description\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Description\", \"Channel Type\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Status History Data",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "ComplaintID",
            "dataType": "int64",
            "sourceColumn": "ComplaintID",
            "formatString": "0",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "ComplaintStatusID",
            "dataType": "int64",
            "sourceColumn": "ComplaintStatusID",
            "formatString": "0",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Status Date",
            "dataType": "dateTime",
            "sourceColumn": "Status Date",
            "formatString": "dd mmmm yyyy",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "38164c93-f7e4-4b16-b54e-da935063345d",
                "defaultHierarchy": {
                  "table": "LocalDateTable_013887ac-37a8-4cb0-a4b8-75cb42c6efb6",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"LongDate\" FormatString=\"dd MMMM yyyy\" /></DateTimes></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Status History Data-98d7907b-ac63-4b53-867b-ed4916eb10ce",
            "mode": "import",
            "queryGroup": "Data Model",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\OneDrive - EnterpriseDNA\\VIRTUAL TRAINING\\Power BI Challenges\\Insurance Complaints\\Insurance - Complain Administration.xlsx\"), null, true),",
                "    StatusHistoryData_Tbl_Table = Source{[Item=\"StatusHistoryData_Tbl\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(StatusHistoryData_Tbl_Table,{{\"ID\", Int64.Type}, {\"ComplaintID\", Int64.Type}, {\"ComplaintStatusID\", Int64.Type}, {\"StatusDate\", type date}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"StatusDate\", \"Status Date\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Priorities",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Priority",
            "dataType": "string",
            "sourceColumn": "Priority",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Priorities-1f4a3066-9e5a-4826-a9f7-73051f7daffb",
            "mode": "import",
            "queryGroup": "Data Model",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\OneDrive - EnterpriseDNA\\VIRTUAL TRAINING\\Power BI Challenges\\Insurance Complaints\\Insurance - Complain Administration.xlsx\"), null, true),",
                "    Priorities_Tbl_Table = Source{[Item=\"Priorities_Tbl\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Priorities_Tbl_Table,{{\"ID\", Int64.Type}, {\"Description\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Description\", \"Priority\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Customers",
        "columns": [
          {
            "name": "CustomerID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "LastName",
            "dataType": "string",
            "sourceColumn": "LastName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "sourceColumn": "FirstName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate",
            "formatString": "dd mmmm yyyy",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "7b7f48e8-884c-4185-9a21-9728f993c851",
                "defaultHierarchy": {
                  "table": "LocalDateTable_d6b79f0e-adab-4246-80b7-8f62ccee5679",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"LongDate\" FormatString=\"dd MMMM yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Customer Type",
            "dataType": "string",
            "sourceColumn": "Customer Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "RegionID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RegionID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "MaritalStatus",
            "dataType": "string",
            "sourceColumn": "MaritalStatus",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Customers-4b0ecbbc-6455-4273-99e3-134f9849d417",
            "mode": "import",
            "queryGroup": "Data Model",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\OneDrive - EnterpriseDNA\\VIRTUAL TRAINING\\Power BI Challenges\\Insurance Complaints\\Insurance - Complain Administration.xlsx\"), null, true),",
                "    Customers_Tbl_Table = Source{[Item=\"Customers_Tbl\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Customers_Tbl_Table,{{\"CustomerID\", Int64.Type}, {\"LastName\", type text}, {\"FirstName\", type text}, {\"BirthDate\", type date}, {\"Gender\", type text}, {\"ParticipantType\", type text}, {\"RegionID\", Int64.Type}, {\"MaritalStatus\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"ParticipantType\", \"Customer Type\"}}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Renamed Columns\",{{\"Gender\", Text.Proper, type text}, {\"Customer Type\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_d6b79f0e-adab-4246-80b7-8f62ccee5679",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_d6b79f0e-adab-4246-80b7-8f62ccee5679-9dac701e-eed5-4509-80f4-55463aea9848",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Customers'[BirthDate])), 1, 1), Date(Year(MAX('Customers'[BirthDate])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "Products",
        "columns": [
          {
            "name": "ProductID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Product Category",
            "dataType": "string",
            "sourceColumn": "Product Category",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Product Sub Category",
            "dataType": "string",
            "sourceColumn": "Product Sub Category",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Product",
            "dataType": "string",
            "sourceColumn": "Product",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Products-6b765f37-a295-454c-a041-8731fa64276b",
            "mode": "import",
            "queryGroup": "Data Model",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\OneDrive - EnterpriseDNA\\VIRTUAL TRAINING\\Power BI Challenges\\Insurance Complaints\\Insurance - Complain Administration.xlsx\"), null, true),",
                "    Products_Tbl_Table = Source{[Item=\"Products_Tbl\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Products_Tbl_Table,{{\"ProductID\", Int64.Type}, {\"ProductCategory\", type text}, {\"ProductSubCategory\", type text}, {\"Product\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"ProductSubCategory\", \"Product Sub Category\"}, {\"ProductCategory\", \"Product Category\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Sources",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Source",
            "dataType": "string",
            "sourceColumn": "Source",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sources-61ec4249-d668-4230-a8a1-87cb92d1d22c",
            "mode": "import",
            "queryGroup": "Data Model",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\OneDrive - EnterpriseDNA\\VIRTUAL TRAINING\\Power BI Challenges\\Insurance Complaints\\Insurance - Complain Administration.xlsx\"), null, true),",
                "    Sources_Tbl_Table = Source{[Item=\"Sources_Tbl\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Sources_Tbl_Table,{{\"ID\", Int64.Type}, {\"Description\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Description\", \"Source\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Brokers",
        "columns": [
          {
            "name": "BrokerID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrokerID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "BrokerCode",
            "dataType": "string",
            "sourceColumn": "BrokerCode",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Broker Name",
            "dataType": "string",
            "sourceColumn": "Broker Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "DistributionNetwork",
            "dataType": "string",
            "sourceColumn": "DistributionNetwork",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Channel",
            "dataType": "string",
            "sourceColumn": "Channel",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "CommissionScheme",
            "dataType": "string",
            "sourceColumn": "CommissionScheme",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Brokers-969c8243-21a1-432b-8fd9-d219646280b1",
            "mode": "import",
            "queryGroup": "Data Model",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\OneDrive - EnterpriseDNA\\VIRTUAL TRAINING\\Power BI Challenges\\Insurance Complaints\\Insurance - Complain Administration.xlsx\"), null, true),",
                "    Brokers_Tbl_Table = Source{[Item=\"Brokers_Tbl\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Brokers_Tbl_Table,{{\"BrokerID\", Int64.Type}, {\"BrokerCode\", type text}, {\"BrokerFullName\", type text}, {\"DistributionNetwork\", type text}, {\"DistributionChannel\", type text}, {\"CommissionScheme\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"BrokerFullName\", \"Broker Name\"}, {\"DistributionChannel\", \"Channel\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Categories",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Active",
            "dataType": "int64",
            "sourceColumn": "Active",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Categories-99cd67a6-bc2e-4c40-a84f-a8a7382a2047",
            "mode": "import",
            "queryGroup": "Data Model",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\OneDrive - EnterpriseDNA\\VIRTUAL TRAINING\\Power BI Challenges\\Insurance Complaints\\Insurance - Complain Administration.xlsx\"), null, true),",
                "    Categories_Tbl_Table = Source{[Item=\"Categories_Tbl\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Categories_Tbl_Table,{{\"ID\", Int64.Type}, {\"Description\", type text}, {\"Active\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Description\", \"Category\"}}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Renamed Columns\",{{\"Category\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Key Measures",
        "partitions": [
          {
            "name": "Key Measures-d0793f4e-d993-4544-be94-00a4c825312a",
            "mode": "import",
            "queryGroup": "Measure Groups",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Complaints",
            "expression": "COUNTROWS( 'Complaints Data' )",
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "New Complaints",
            "expression": [
              "",
              "CALCULATE( [Total Complaints],",
              "    USERELATIONSHIP( Dates[Date], 'Complaints Data'[Complain Date] ) )"
            ],
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Current Complaints",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Complaints],",
              "    FILTER(",
              "        VALUES( 'Complaints Data'[Complain Date] ),",
              "          'Complaints Data'[Complain Date] <= MAX( Dates[Date] )",
              "    ),",
              "    FILTER(",
              "        VALUES( 'Complaints Data'[Completion Date] ),",
              "          'Complaints Data'[Completion Date] >= MIN( Dates[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Open Complaints",
            "expression": [
              "",
              "CALCULATE( [Total Complaints], FILTER( Statuses, Statuses[Status] <> \"CLOSED\") )"
            ],
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Total New Complaints",
            "expression": [
              "",
              "CALCULATE( [Total Complaints], FILTER( Statuses, Statuses[Status] = \"NEW\") )"
            ],
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "In Progress Complaints",
            "expression": [
              "",
              "CALCULATE( [Total Complaints], FILTER( Statuses, Statuses[Status] = \"IN PROGRESS\") )"
            ],
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Dates Selected",
            "expression": [
              "",
              "VAR Mindate = MIN( Dates[Date] )",
              "VAR Maxdate = MAX( Dates[Date] )",
              "",
              "RETURN",
              "FORMAT( Mindate, \"dd mmm, yyyy\" ) & \" - \" & FORMAT( Maxdate, \"dd mmm, yyyy\" )"
            ],
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Outstanding Complaints",
            "expression": [
              "",
              "CALCULATE( [Total Complaints], FILTER( Statuses, Statuses[Status] = \"Outstanding\") )"
            ],
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Assigned Complaints",
            "expression": [
              "",
              "CALCULATE( [Total Complaints], FILTER( Statuses, Statuses[Status] = \"Assigned To\") )"
            ],
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Satification Logic",
            "expression": [
              "",
              "SWITCH( TRUE(),",
              "    SELECTEDVALUE( 'Complaints Data'[Satisfaction Level] ) = \"Satisfied\", 1,",
              "    SELECTEDVALUE( 'Complaints Data'[Satisfaction Level] ) = \"No Data\", 2,",
              "    SELECTEDVALUE( 'Complaints Data'[Satisfaction Level] ) = \"Not Satisfied\", 3,",
              "0 )"
            ],
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Complaint Follow Ups",
            "expression": [
              "",
              "VAR NotClosed =",
              "FILTER(",
              "    FILTER( ALL( 'Complaints Data' ),'Complaints Data'[Days Since Complaint] > 150 ),",
              "  'Complaints Data'[ComplainStatusID] <> 9",
              ") ",
              "",
              "RETURN",
              "COUNTROWS( NotClosed )"
            ],
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Unsatified Complaints",
            "expression": [
              "",
              "VAR Unsatisfied =",
              "FILTER(",
              "    FILTER( ALL( 'Complaints Data' ), 'Complaints Data'[ComplainStatusID] <> 9 ),",
              "  'Complaints Data'[Satisfaction Level] = \"Not Satisfied\"",
              ") ",
              "",
              "RETURN",
              "IF( ISBLANK( COUNTROWS( Unsatisfied ) ), 0, COUNTROWS( Unsatisfied ) )"
            ],
            "formatString": "0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Transparent",
            "expression": "\"#ffffff00\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_013887ac-37a8-4cb0-a4b8-75cb42c6efb6",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_013887ac-37a8-4cb0-a4b8-75cb42c6efb6-7b62b62d-fb02-449d-804d-0d12caf54b6c",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Status History Data'[Status Date])), 1, 1), Date(Year(MAX('Status History Data'[Status Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "7b7f48e8-884c-4185-9a21-9728f993c851",
        "fromTable": "Customers",
        "fromColumn": "BirthDate",
        "toTable": "LocalDateTable_d6b79f0e-adab-4246-80b7-8f62ccee5679",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "fb6c77ba-baee-40ae-94b9-4178a41c0330",
        "fromTable": "Complaints Data",
        "fromColumn": "BrokerID",
        "toTable": "Brokers",
        "toColumn": "BrokerID"
      },
      {
        "name": "8fced164-f599-41c5-9341-5c41908f7165",
        "fromTable": "Complaints Data",
        "fromColumn": "ProductID",
        "toTable": "Products",
        "toColumn": "ProductID"
      },
      {
        "name": "a0bcfb85-de9b-4b49-8194-2b2629419046",
        "fromTable": "Complaints Data",
        "fromColumn": "CustomerID",
        "toTable": "Customers",
        "toColumn": "CustomerID"
      },
      {
        "name": "aa1c8996-173e-4e72-a1eb-a6fb57396d4e",
        "fromTable": "Complaints Data",
        "fromColumn": "Complain Date",
        "toTable": "Dates",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "622c8e7c-acb9-4511-8e9b-b76d19c1c2ce",
        "fromTable": "Complaints Data",
        "fromColumn": "ComplainStatusID",
        "toTable": "Statuses",
        "toColumn": "ID"
      },
      {
        "name": "eef2fae6-8833-4598-b397-22c6b9cd167b",
        "fromTable": "Complaints Data",
        "fromColumn": "ComplainSourceID",
        "toTable": "Sources",
        "toColumn": "ID"
      },
      {
        "name": "62474145-fea9-476a-b5a5-8bfb673689e8",
        "fromTable": "Complaints Data",
        "fromColumn": "ComplainTypeID",
        "toTable": "Types",
        "toColumn": "ID"
      },
      {
        "name": "598ecd1e-932a-4acb-81cf-2519b1327611",
        "fromTable": "Complaints Data",
        "fromColumn": "ComplainCategoryID",
        "toTable": "Categories",
        "toColumn": "ID"
      },
      {
        "name": "58be4a0d-dcfa-4a55-8d71-eccbd3bdbdb6",
        "fromTable": "Complaints Data",
        "fromColumn": "ComplainPriorityID",
        "toTable": "Priorities",
        "toColumn": "ID"
      },
      {
        "name": "927ee481-53e7-4fc1-874a-5090dc4382fa",
        "fromTable": "Complaints Data",
        "fromColumn": "Completion Date",
        "toTable": "Dates",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "f62a5826-948f-4ee5-93c0-4edbff595d37",
        "fromTable": "Customers",
        "fromColumn": "RegionID",
        "toTable": "Regions",
        "toColumn": "id"
      },
      {
        "name": "38164c93-f7e4-4b16-b54e-da935063345d",
        "fromTable": "Status History Data",
        "fromColumn": "Status Date",
        "toTable": "LocalDateTable_013887ac-37a8-4cb0-a4b8-75cb42c6efb6",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "1e7204ef-19b7-49b2-98ff-b13145a7a0c7",
        "fromTable": "Status History Data",
        "fromColumn": "ID",
        "toTable": "Complaints Data",
        "toColumn": "ID"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Version": "1.0.0",
            "Language": "en-US",
            "DynamicImprovement": "HighConfidence"
          },
          "contentType": "json"
        }
      }
    ],
    "expressions": [
      {
        "name": "State Regions",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\OneDrive - EnterpriseDNA\\VIRTUAL TRAINING\\Power BI Challenges\\Insurance Complaints\\Insurance - Complain Administration.xlsx\"), null, true),",
          "    StateRegions_Tbl_Table = Source{[Item=\"StateRegions_Tbl\",Kind=\"Table\"]}[Data],",
          "    #\"Changed Type\" = Table.TransformColumnTypes(StateRegions_Tbl_Table,{{\"State Code\", type text}, {\"State\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "queryGroup": "Supporting Queries",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dates Query",
        "kind": "m",
        "expression": [
          "let fnDateTable = (StartDate as date, EndDate as date, optional FYStartMonth as number, optional Holidays as list, optional WDStartNum as number ) as table =>",
          "  let",
          "    FYStartMonth = if List.Contains( {1..12}, FYStartMonth ) then FYStartMonth else 1,",
          "    //the WDStartNum parameter allows you to set Weekday numbering running from 0-6 or 1-7 but first day of the week will remain Monday",
          "    WDStart = if List.Contains( {0, 1}, WDStartNum ) then WDStartNum else 0,",
          "    CurrentDate = Date.From(DateTime.FixedLocalNow()),",
          "    DayCount = Duration.Days(Duration.From(EndDate - StartDate))+1,",
          "    Source = List.Dates(StartDate,DayCount,#duration(1,0,0,0)),",
          "    AddToday = if EndDate < CurrentDate then List.Combine( {Source, {CurrentDate}}) else Source,",
          "    TableFromList = Table.FromList(AddToday, Splitter.SplitByNothing()),",
          "    ChangedType = Table.TransformColumnTypes(TableFromList,{{\"Column1\", type date}}),",
          "    RenamedColumns = Table.RenameColumns(ChangedType,{{\"Column1\", \"Date\"}}),",
          "    InsertYear = Table.AddColumn(RenamedColumns, \"Year\", each Date.Year([Date]), type number),",
          "    InsertQuarter = Table.AddColumn(InsertYear, \"QuarterOfYear\", each Date.QuarterOfYear([Date]), type number),",
          "    InsertMonth = Table.AddColumn(InsertQuarter, \"MonthOfYear\", each Date.Month([Date]), type number),",
          "    InsertDay = Table.AddColumn(InsertMonth, \"DayOfMonth\", each Date.Day([Date]), type number),",
          "    InsertDayInt = Table.AddColumn(InsertDay, \"DateInt\", each [Year] * 10000 + [MonthOfYear] * 100 + [DayOfMonth], type number),",
          "    InsertMonthName = Table.AddColumn(InsertDayInt, \"Month Name\", each Date.ToText([Date], \"MMMM\"), type text),",
          "    InsertCalendarMonth = Table.AddColumn(InsertMonthName, \"Month & Year\", each (try(Text.Range([Month Name],0,3)) otherwise [Month Name]) & \" \" & Number.ToText([Year]), type text),",
          "    InsertCalendarQtr = Table.AddColumn(InsertCalendarMonth, \"Quarter & Year\", each \"Q\" & Number.ToText([QuarterOfYear]) & \" \" & Number.ToText([Year]), type text),",
          "    InsertDayWeek = Table.AddColumn(InsertCalendarQtr, \"DayOfWeek\", each Date.DayOfWeek([Date]) + WDStart, Int64.Type),",
          "    InsertDayName = Table.AddColumn(InsertDayWeek, \"DayOfWeekName\", each Date.ToText([Date], \"dddd\"), type text),",
          "    InsertWeekEnding = Table.AddColumn(InsertDayName, \"WeekEnding\", each Date.EndOfWeek( [Date], Day.Monday), type date),",
          "    InsertMonthEnding = Table.AddColumn(InsertWeekEnding, \"MonthEnding\", each Date.EndOfMonth([Date]), type date),",
          "    InsertWeekNumber= Table.AddColumn(InsertMonthEnding, \"ISO Weeknumber\", each",
          "      if Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)=0",
          "      then Number.RoundDown((Date.DayOfYear(#date(Date.Year([Date])-1,12,31))-(Date.DayOfWeek(#date(Date.Year([Date])-1,12,31), Day.Monday)+1)+10)/7)",
          "      else if (Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)=53 and (Date.DayOfWeek(#date(Date.Year([Date]),12,31), Day.Monday)+1<4))",
          "      then 1 else Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7), type number),",
          "    InsertISOyear = Table.AddColumn(InsertWeekNumber, \"ISO Year\", each Date.Year( Date.AddDays( Date.StartOfWeek([Date], Day.Monday), 3 )),  Int64.Type),",
          "    BufferTable = Table.Buffer(Table.Distinct( InsertISOyear[[ISO Year], [DateInt]])),",
          "    InsertISOday = Table.AddColumn(InsertISOyear, \"ISO Day of Year\", (OT) => Table.RowCount( Table.SelectRows( BufferTable, (IT) => IT[DateInt] <= OT[DateInt] and IT[ISO Year] = OT[ISO Year])),  Int64.Type),",
          "    InsertCalendarWk = Table.AddColumn(InsertISOday, \"Week & Year\", each Text.From([ISO Year]) & \"-\" & Text.PadStart( Text.From( [ISO Weeknumber] ), 2, \"0\"), type text ),",
          "    InsertWeeknYear = Table.AddColumn(InsertCalendarWk, \"WeeknYear\", each [ISO Year] * 10000 + [ISO Weeknumber] * 100,  Int64.Type),",
          "",
          "    InsertMonthnYear = Table.AddColumn(InsertWeeknYear , \"MonthnYear\", each [Year] * 10000 + [MonthOfYear] * 100, type number),",
          "    InsertQuarternYear = Table.AddColumn(InsertMonthnYear, \"QuarternYear\", each [Year] * 10000 + [QuarterOfYear] * 100, type number),",
          "    AddFY = Table.AddColumn(InsertQuarternYear, \"Fiscal Year\", each \"FY\" & (if [MonthOfYear] >= FYStartMonth then Text.PadEnd( Text.End( Text.From([Year] +1), 2), 2, \"0\") else Text.End( Text.From([Year]), 2)), type text),",
          "    AddFQ = Table.AddColumn(AddFY, \"Fiscal Quarter\", each \"FQ\" & Text.From( Number.RoundUp( Date.Month( Date.AddMonths( [Date], - (FYStartMonth -1) )) / 3 )), type text),",
          "    AddFM = Table.AddColumn(AddFQ, \"Fiscal Period\", each if [MonthOfYear] >= FYStartMonth then [MonthOfYear] - (FYStartMonth-1) else [MonthOfYear] + (12-FYStartMonth+1), type text),",
          "",
          "    InsertIsAfterToday = Table.AddColumn(AddFM, \"IsAfterToday\", each not ([Date] <= Date.From(CurrentDate)), type logical),",
          "    InsertIsWorkingDay = Table.AddColumn(InsertIsAfterToday, \"IsWorkingDay\", each if Date.DayOfWeek([Date], Day.Monday) > 4 then false else true, type logical),",
          "    InsertIsHoliday = Table.AddColumn(InsertIsWorkingDay, \"IsHoliday\", each if Holidays = null then \"Unknown\" else List.Contains( Holidays, [Date] ), if Holidays = null then type text else type logical),",
          "    InsertIsBusinessDay = Table.AddColumn(InsertIsHoliday, \"IsBusinessDay\", each if [IsWorkingDay] = true and [IsHoliday] <> true then true else false, type logical),",
          "    InsertDayType = Table.AddColumn(InsertIsBusinessDay, \"Day Type\", each if [IsHoliday] = true then \"Holiday\" else if [IsWorkingDay] = false then \"Weekend\" else if [IsWorkingDay] = true then \"Weekday\" else null, type text),",
          "",
          "    //InsertDayOffset = Table.AddColumn(InsertDayType, \"DayOffset\", each Number.From([Date] - CurrentDate), type number),  //if you enable DayOffset, don't forget to adjust the PreviousStepName in the next line of code.",
          "    InsertWeekOffset = Table.AddColumn(InsertDayType, \"WeekOffset\", each (Number.From(Date.StartOfWeek([Date], Day.Monday))-Number.From(Date.StartOfWeek(CurrentDate, Day.Monday)))/7, type number),",
          "    InsertMonthOffset = Table.AddColumn(InsertWeekOffset, \"MonthOffset\", each ((12 * Date.Year([Date])) +  Date.Month([Date])) - ((12 * Date.Year(Date.From(CurrentDate))) +  Date.Month(Date.From(CurrentDate))), type number),",
          "    InsertQuarterOffset = Table.AddColumn(InsertMonthOffset, \"QuarterOffset\", each ((4 * Date.Year([Date])) +  Date.QuarterOfYear([Date])) - ((4 * Date.Year(Date.From(CurrentDate))) +  Date.QuarterOfYear(Date.From(CurrentDate))), type number),",
          "    InsertYearOffset = Table.AddColumn(InsertQuarterOffset, \"YearOffset\", each Date.Year([Date]) - Date.Year(Date.From(CurrentDate)), type number),",
          "",
          "    IdentifyCurrentDate = Table.SelectRows(InsertYearOffset, each ([Date] = CurrentDate)),",
          "    CurrentYear = IdentifyCurrentDate{0}[Year],",
          "    CurrentMonth = IdentifyCurrentDate{0}[MonthOfYear],",
          "    InsertFYoffset = Table.AddColumn(InsertYearOffset, \"FiscalYearOffset\", each try (if [MonthOfYear] >= FYStartMonth then [Year]+1 else [Year]) - ",
          "      (if CurrentMonth >= FYStartMonth then CurrentYear+1 else CurrentYear) otherwise null, type number),",
          "    RemoveToday = if EndDate < CurrentDate then Table.SelectRows(InsertFYoffset, each ([Date] <> CurrentDate)) else InsertFYoffset,",
          "    InsertCompletedWeek = Table.AddColumn(RemoveToday, \"WeekCompleted\", each [WeekEnding] < Date.From(Date.EndOfWeek(CurrentDate)), type logical),",
          "    InsertCompletedMonth = Table.AddColumn(InsertCompletedWeek, \"MonthCompleted\", each [MonthEnding] < Date.From(Date.EndOfMonth(CurrentDate)), type logical),",
          "    InsertCompletedQuarter = Table.AddColumn(InsertCompletedMonth, \"QuarterCompleted\", each Date.EndOfQuarter([Date]) < Date.From(Date.EndOfQuarter(CurrentDate)), type logical),",
          "    InsertChangedType = Table.TransformColumnTypes(InsertCompletedQuarter,{{\"Year\", Int64.Type}, {\"QuarterOfYear\", Int64.Type}, {\"MonthOfYear\", Int64.Type}, {\"DayOfMonth\", Int64.Type}, {\"DateInt\", Int64.Type}, {\"DayOfWeek\", Int64.Type}, {\"ISO Weeknumber\", Int64.Type}, {\"WeeknYear\", Int64.Type}, {\"MonthnYear\", Int64.Type}, {\"QuarternYear\", Int64.Type}, {\"Fiscal Period\", Int64.Type}, {\"WeekOffset\", Int64.Type}, {\"MonthOffset\", Int64.Type}, {\"QuarterOffset\", Int64.Type}, {\"YearOffset\", Int64.Type}, {\"FiscalYearOffset\", Int64.Type}})",
          "  in",
          "  InsertChangedType",
          "in",
          "fnDateTable"
        ],
        "queryGroup": "Parameter Query",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ]
      }
    ],
    "queryGroups": [
      {
        "folder": "Parameter Query",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "Data Model",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ]
      },
      {
        "folder": "Supporting Queries",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ]
      },
      {
        "folder": "Measure Groups",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.90.782.0 (21.02)"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Dates\",\"Brokers\",\"Categories\",\"Customers\",\"Priorities\",\"Products\",\"Regions\",\"Sources\",\"State Regions\",\"Statuses\",\"Types\",\"Complaints Data\",\"Status History Data\",\"Dates Query\",\"Key Measures\"]"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Translations\"]}"
      }
    ]
  }
}